<?php
	header("Access-Control-Allow-Origin:*");
	
	$data="[
		{
			\"ranking\":\"1\",
			\"classID\":\"1\",
			\"goodsID\":\"4\",
			\"buyernumber\":\"103893\",
			\"discount\":\"8.0折\",
			\"oldPrice\":\"280元\",
			\"goodsName\":\"大五编发财树\",
			\"goodsListImg\":\"http://congcong.duapp.com/flower/one/facai/dawubian.png\",
			\"newPrice\":\"224元\",
			\"imgsUrl\":\"http://congcong.duapp.com/flower/one/facai/dawubian.png\",
			\"className\":\"绿植\",
			\"goodsBenUrl\":\"http://congcong.duapp.com/flower/one/facai/dawubian.png\",
			\"detail\":\"发财树又名马拉巴栗、瓜栗、中美木棉、鹅掌钱.为木棉科常绿小乔木.原产拉丁美洲的哥斯达黎加、澳洲及太平洋中的一些小岛屿,我国南部热带地区亦有分布.发财树为多年生常绿灌木,性喜温暖、湿润,向阳或稍有疏荫的环境.是大众化的盆栽,气温满足20℃以上的温度就可以播种,播种发芽率还是挺高的.由于发财树的名称深受商家及一般市民的欢迎,立株形状美、叶色亮绿,树干呈锤形,盆载后适于在家内布置和美化使用,所以,在中国花卉市场上发展甚快.每逢节日,各宾馆、饭店、商家及市民多争相采购.以图吉祥如意.\",
			\"plantSays\":\"招财进宝,财源滚滚,兴旺发达,前程似锦\"
		},
		{
			\"ranking\":\"2\",
			\"classID\":\"1\",
			\"goodsID\":\"18\",
			\"goodsName\":\"平安树\",
			\"buyernumber\":\"113893\",
			\"discount\":\"9.0折\",
			\"oldPrice\":\"350元\",
			\"goodsListImg\":\"http://congcong.duapp.com/flower/one/other/pinganshu.jpeg\",
			\"newPrice\":\"314元\",
			\"imgsUrl\":\"http://congcong.duapp.com/flower/one/other/pinganshu.jpeg\",
			\"className\":\"绿植\",
			\"goodsBenUrl\":\"http://congcong.duapp.com/flower/one/other/pinganshu.jpeg\",
			\"detail\":\"平安树,原名：兰屿肉桂；别名：红头屿肉桂、红头山肉桂、芳兰山肉桂、大叶肉桂、台湾肉桂等,拉丁文名：Cinnamomum kotoense Kanehira et Sasaki .为樟科、樟属常绿小乔木,其原名为兰屿肉桂即中国台湾的兰屿岛。原多产于兰屿岛,是一种翠绿吉祥的兰屿肉桂(肉桂、平安树、平安木)。产中国台湾南部(兰屿)。平安树的来历却有一段美丽动人的传说：相传很久以前,有一条天龙受伤后落到今九台市莽卡满族乡境内不能行动,由于太阳晒和干旱少雨,天龙奄奄一息。当地群众闻讯后自发前来给这条龙搭了凉棚,防止太阳晒,并每天轮流给龙浇水,等到七七四“十九天后,这条龙伤愈后,腾云驾雾而起,它为了感谢这些好心的百姓救命之恩,保佑他们幸福平安,把自己的一枚龙珠投掷到今九台市胡家青松岭上,不久这枚龙珠变成一棵榆树,该树形态长得龙盘虎距,三伏天会流泪,那是天龙的感恩泪,谁喝了感恩泪,谁就心想事成,冬天该树青翠,那是天龙祝福,谁能看到谁就万事如意。后来人们把天龙养伤之地起名叫龙棚(今莽卡龙棚村),龙珠变的树叫平安树几百年来,每逢初一、十五都有来自全国各地的人们前来拜祭,乞求平安、合家幸福、万事如意。平安树意寓祈求平安、合家幸福、万事如意等美好的祝愿。平安树其皮可以入药,有祛风散寒,止痛化瘀,活血健胃之功效,又因为其植物体内富含桂皮油,又能散发出矫正异味,净化空气的香味,所以人们给它取了一个吉祥的名字平安树。\",
			\"plantSays\":\"祈求平安,阖家幸福,万事如意\"
		},
		{
			\"ranking\":\"3\",
			\"classID\":\"1\",
			\"goodsID\":\"57\",
			\"goodsName\":\"单杆幸福树\",
			\"buyernumber\":\"134293\",
			\"discount\":\"8.5折\",
			\"oldPrice\":\"310元\",
			\"goodsListImg\":\"http://congcong.duapp.com/flower/one/xingfu/dangan.jpg\",
			\"newPrice\":\"264元\",
			\"imgsUrl\":\"http://congcong.duapp.com/flower/one/xingfu/dangan.jpg\",
			\"className\":\"绿植\",
			\"goodsBenUrl\":\"http://congcong.duapp.com/flower/one/xingfu/dangan.jpg\",
			\"detail\":\"“幸福树”学名菜豆树,它性喜高温多湿、阳光足的环境。耐高温,畏寒冷,宜湿润,忌干燥。栽培宜用疏松肥沃、排水良好、富含有机质的壤土和沙质壤土。花期5月至9月,果期10月至12月。幸福树树形美观,树姿优雅．花期长,花朵大,花香淡雅,花色美且多,几乎每个枝条都有花序；一个花序轴上的许多花朵往往同时开放,排成一长串金黄色的花带,令人赏心悦目。因此．具有极高的观赏价值和园林应用前景,是热带、南亚热带地区城镇、街道、公园、庭院等园林绿化的优良树种。\",
			\"plantSays\":\"平安、幸福\"
		}
	]";
	
	echo $data;
?>